// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Balance } from "./Balance";

export type Account = { address: string, balance: Balance, nonce: number, first_seen_ms: number, last_active_ms: number, };
