// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filters for `/accounts/{address}/ats`. Placeholder.
 */
export type AccountAtsFilters = Record<string, never>;
