// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeId } from "./EnvelopeId";

/**
 * One per-beneficiary allocation, with its claimable amount resolved at the
 * chain head (so the UI doesn't recompute vesting math on every render).
 */
export type Allocation = { id: number, envelope: EnvelopeId, beneficiary: string, total: string, upfront: string, vested_total: string, released: string, 
/**
 * Block at which vesting starts (= max(allocation.start, envelope.cliff)).
 */
start_block: string, 
/**
 * Vested amount currently claimable at the chain head (post-released).
 */
claimable_now: string, 
/**
 * 0..=100 share of `vested_total` already released.
 */
percent_vested: number, };
