// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flat ATS version feed item (one row per version, sorted by time desc).
 */
export type AtsFeedItem = { ats_id: number, owner: string, version_index: number, is_initial: boolean, is_latest: boolean, version_count: number, commitment: string, protocol_version: number, block_number: string, extrinsic_id: string, timestamp_ms: number, signer: string, };
