// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filters for `/ats/feed`. Placeholder.
 */
export type AtsFeedFilters = Record<string, never>;
