// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filters for `/ats`. Placeholder — no fields planned yet.
 */
export type AtsFilters = Record<string, never>;
