// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtsVersion } from "./AtsVersion";
import type { Deposit } from "./Deposit";

export type AtsRecord = { ats_id: number, owner: string, created_at_ms: number, created_at_block: string, version_count: number, deposits: Array<Deposit>, total_deposit: string, versions: Array<AtsVersion>, };
