// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AtsStats = { total: number, total_versions: number, last_24h: number, last_7d: number, last_30d: number, unique_owners: number, avg_per_day: number, protocol_version: number, genesis_block: string, first_registered_at_ms: number, total_deposited: string, multi_version_share: number, };
