// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One version in an ATS registry entry.
 */
export type AtsVersion = { version_index: number, commitment: string, protocol_version: number, created_at_ms: number, block_number: string, extrinsic_index: number, 
/**
 * `"<block>-<index>"`.
 */
extrinsic_id: string, fee: string, signer: string, };
