// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Balance breakdown for an account (in planck). Chain has a fixed supply
 * and no staking, so only transferable + reserved.
 */
export type Balance = { total: string, transferable: string, reserved: string, };
