// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filters for `/blocks`. Phase 3 ships `finalized` and `min_extrinsics`;
 * `spec_version` / `author` stay reserved until the UI actually needs
 * them.
 */
export type BlockFilters = { 
/**
 * `true` → only finalized blocks, `false` → only non-finalized. The
 * indexed path stores nothing but finalized rows, so `Some(false)`
 * short-circuits to an empty page there; the mock surface still has
 * a "pending tip" window where the distinction is meaningful.
 */
finalized: boolean | null, 
/**
 * Minimum number of extrinsics in the block. Cheap because the count
 * is already denormalized on `blocks.extrinsic_count` — no join back
 * to `extrinsics`.
 */
min_extrinsics: number | null, };
