// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventField } from "./EventField";
import type { EventPhase } from "./EventPhase";

/**
 * Block-scoped event: one row per emitted event, preserving the phase so
 * the UI can render Initialization/Finalization events alongside the ones
 * attached to extrinsics.
 */
export type BlockEvent = { block_number: string, 
/**
 * Running event index within the block (Substrate's canonical
 * `<block>-<index>` event id uses this).
 */
index: number, phase: EventPhase, module: string, name: string, fields: Array<EventField>, 
/**
 * Timestamp of the enclosing block. Redundant with the block's own
 * timestamp on per-block queries, but carried here so the latest-
 * events feed can render each row's age without a second lookup.
 */
timestamp_ms: number, };
