// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A substrate block.
 */
export type Block = { number: string, hash: string, parent_hash: string, state_root: string, extrinsics_root: string, 
/**
 * Milliseconds since Unix epoch (in the mock timeline).
 */
timestamp_ms: number, finalized: boolean, extrinsic_count: number, event_count: number, author: string, author_name: string, ref_time: string, ref_time_pct: number, proof_size: string, spec_version: number, size_bytes: number, };
