// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution result of an extrinsic (or dispatched call).
 */
export type CallResult = "Success" | "Failed";
