// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One decoded argument of an extrinsic call. Same shape as
 * [`EventField`] plus a `type_name` sourced from the runtime metadata
 * (e.g. `"MultiAddress"`, `"Compact<Balance>"`) so the UI can label the
 * parameter without baking the pallet catalogue into the frontend.
 */
export type CallField = { name: string | null, type_name: string | null, value: string, };
