// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Budget pockets defined at genesis. Wire form is lowercase strings the
 * frontend uses verbatim in `/token/envelopes/:id` URLs.
 */
export type EnvelopeId = "teams" | "kol" | "private1" | "private2" | "public1" | "public2" | "public3" | "public4" | "airdrop" | "community-rewards" | "listing" | "research-development" | "reserve";
