// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeId } from "./EnvelopeId";

/**
 * One genesis envelope: cap, vesting params, distribution progress.
 */
export type EnvelopeInfo = { id: EnvelopeId, label: string, 
/**
 * Pallet sub-account holding the envelope balance.
 */
account: string, total_cap: string, distributed: string, 
/**
 * 0..=100 percentage paid up front at allocation time.
 */
upfront_pct: number, cliff_blocks: string, vesting_duration_blocks: string, unique_beneficiary: string | null, 
/**
 * Number of allocations issued from this envelope.
 */
allocation_count: number, };
