// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Allocation } from "./Allocation";
import type { EnvelopeInfo } from "./EnvelopeInfo";

/**
 * Full detail for a single envelope: config + allocation list.
 */
export type EnvelopeDetail = { envelope: EnvelopeInfo, allocations: Array<Allocation>, };
