// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EpochInfo = { index: string, head_block: string, next_payout_block: string, epoch_duration_blocks: string, };
