// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Substrate block-event phase. Events with `Initialization` fire before any
 * extrinsic (e.g. `session.NewSession` on a session-change block);
 * `ApplyExtrinsic(idx)` events are the ones emitted while dispatching
 * extrinsic `idx`; `Finalization` events fire in `on_finalize`. Polkadot.js
 * displays all three — the explorer used to drop the first and last.
 */
export type EventPhase = { "kind": "initialization" } | { "kind": "apply_extrinsic", index: number, } | { "kind": "finalization" };
