// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filters for `/events`. Uses the `events_pallet_variant_idx` composite
 * index — querying by `variant` alone still hits the index prefix.
 */
export type EventFilters = { pallet: string | null, variant: string | null, };
