// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One decoded field of an event. `name` is `None` for tuple-style
 * variants (`#[codec(index)]` positional fields); `value` is the
 * `scale_value::Value` rendered via its `Display` impl — good enough
 * for the UI and stable across runtime versions.
 */
export type EventField = { name: string | null, value: string, };
