// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventField } from "./EventField";

/**
 * Event emitted during extrinsic application. `fields` is empty when
 * the backend didn't decode the payload (mock, or a decode error
 * against the current metadata).
 */
export type EventRef = { module: string, name: string, fields: Array<EventField>, };
