// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallResult } from "./CallResult";
import type { EventRef } from "./EventRef";
import type { ExtrinsicArgs } from "./ExtrinsicArgs";

export type Extrinsic = { 
/**
 * `"<block>-<index>"`.
 */
id: string, block_number: string, index: number, hash: string, module: string, call: string, signed: boolean, signer: string | null, args: ExtrinsicArgs, result: CallResult, nonce: number | null, tip: string, fee: string, timestamp_ms: number, events: Array<EventRef>, };
