// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallResult } from "./CallResult";

/**
 * Filters for `/extrinsics`. Phase 3 ships the four UX-critical fields
 * (`signed`, `status`, `pallet`, `call`); `signer` is reserved because a
 * proper address lookup belongs on the account detail page, not in the
 * generic feed.
 */
export type ExtrinsicFilters = { 
/**
 * `true` → only signed extrinsics, `false` → only unsigned
 * (inherents). Maps to `signer IS NOT NULL` / `signer IS NULL` on
 * the SQL side. The default feed still hides the per-block
 * timestamp inherent (`idx=0 + unsigned`) to avoid drowning the
 * list; `signed == Some(false)` or `pallet == "Timestamp"` opens
 * the hole back up so the caller can actually see it.
 */
signed: boolean | null, 
/**
 * Exact pallet match (case-sensitive — metadata pallets are
 * `snake_case` on substrate). Uses the
 * `extrinsics_pallet_call_idx` composite index.
 */
pallet: string | null, 
/**
 * Exact call name. Usually paired with `pallet` so the composite
 * index can prune aggressively; alone it still falls back to a
 * secondary index scan.
 */
call: string | null, 
/**
 * Success / Failed. Maps to `success = true` / `success = false`.
 * Accepts `success` / `failed` in query params too — [`CallResult`]'s
 * default deserializer would only take `Success` / `Failed`, which
 * looks wrong in a URL.
 */
status: CallResult | null, };
