// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallField } from "./CallField";

/**
 * Arguments of an extrinsic call. The generic [`Decoded`](Self::Decoded)
 * shape is produced by a metadata-driven walk over `args_scale`; any
 * call we can't resolve (unknown pallet / variant, truncated bytes,
 * runtime upgrade that removed the call) falls back to
 * [`Raw`](Self::Raw) so the Parameters tab still shows the payload.
 */
export type ExtrinsicArgs = { "Decoded": { fields: Array<CallField>, } } | { "Raw": { hex: string, } };
