// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Traffic-light states used by the banner. Ordered from best to
 * worst so downstream comparisons (e.g. "any state worse than
 * CatchingUp?") stay obvious.
 */
export type IndexerState = "Healthy" | "CatchingUp" | "Backfilling" | "Offline";
