// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexerState } from "./IndexerState";

/**
 * Snapshot of one network's indexer pose, consumed by the banner.
 * All optional fields stay `None` when a reading isn't available yet
 * (cold boot, no DB configured) so the UI can fall back to a
 * "healthy" rendering without guessing.
 */
export type IndexerStatus = { 
/**
 * Network this status describes — matches `NetworkSpec::id`.
 */
network_id: string, state: IndexerState, 
/**
 * Latest finalized block number observed on the chain. `None`
 * before the finalized watcher has fired once.
 */
finalized_head: string | null, 
/**
 * Latest block the indexer has persisted for this network.
 */
indexer_head: string | null, 
/**
 * `finalized_head - indexer_head` when both are known.
 */
live_lag_blocks: string | null, 
/**
 * Number of finalized blocks already indexed.
 */
backfill_done: string, 
/**
 * Expected total once backfill completes.
 */
backfill_total: string, 
/**
 * `backfill_done / backfill_total * 100`, clamped to `[0, 100]`.
 */
backfill_pct: number, };
