// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Static, compile-time description of a mock chain.
 *
 * `Serialize` is derived so the `/api/v1/networks` handler can emit
 * the catalogue directly; `&'static str` fields serialise as strings.
 * No `Deserialize` on purpose — the wire contract is one-way and the
 * server never ingests this shape from a client. The internal mock
 * generator fields (seed, genesis, authors, ats_blocks_per) are
 * skipped on both sides so they never leak into the TS bindings or
 * the JSON response.
 */
export type NetworkSpec = { id: string, name: string, kind: string, testnet: boolean, token: string, block_time_secs: string, spec_version: number, 
/**
 * Runtime's on-chain `spec_name` (from `Core_version`). Static here so
 * mock builds and first-paint SSR have a value; the `/networks` handler
 * overrides it with the live value when RPC is connected.
 */
spec_name: string, 
/**
 * SS58 address-format prefix (`ss58Format` in `system_properties`). Static
 * here so mock builds and first-paint SSR can encode addresses without
 * reaching the node; the `/networks` handler overrides it with the live
 * value when RPC is connected, and every backend address-encoding path
 * reads the live value via the per-client cache so on-disk DB rows
 * (stored as raw 32-byte keys) surface under the correct prefix per
 * network. 42 is the generic-Substrate default (addresses starting with
 * `5`); override per chain once the authoritative value is known.
 */
ss58_prefix: number, endpoint: string, };
