// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query-param shape shared by every paginated endpoint. Handlers extract
 * it via `axum::extract::Query`; the frontend mirrors it through the
 * `usePaginatedList` composable so both ends agree on field names.
 */
export type PageRequest = { count: number, cursor: string | null, };
