// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageInfo } from "./PageInfo";

/**
 * Paginated list response. Every `/api/v1/` list endpoint returns this
 * shape so the frontend binds once (see `usePaginatedList`).
 */
export type Page<T> = { items: Array<T>, page_info: PageInfo, };
