// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata attached to a [`Page<T>`]. `has_more` is always accurate
 * (derived from the fetch-N+1 trick); `next_cursor` is `None` on the
 * last page; `total` is populated only when cheap to compute.
 */
export type PageInfo = { 
/**
 * Overall row count for the query (filters applied). `None` when the
 * backend has no cheap source for it — callers must not assume
 * `total` reflects the number of items currently loaded.
 */
total: string | null, 
/**
 * Opaque (to the client) cursor to pass back as `?cursor=…` for the
 * next page. `None` iff `has_more == false`.
 */
next_cursor: string | null, 
/**
 * True iff at least one more row exists beyond the current page.
 */
has_more: boolean, };
