// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the `system.set_code` timeline. `first_block` is the
 * earliest block observed running this spec version — either the
 * chain's genesis (for the pre-upgrade runtime) or the block in which
 * the `system.CodeUpdated` event landed. `None` means "the backend
 * couldn't determine a deployment block" (e.g. the RPC-only fallback
 * on non-indexed networks); distinct from `Some(0)`, which is a real
 * value meaning "deployed at genesis".
 *
 * `first_block_timestamp_ms` is an `Option` for the same reason and
 * also because Substrate's genesis block has no `timestamp.set`
 * inherent — the indexer stores the missing value as `0`, and
 * surfacing it as a raw epoch-ms would label genesis as "1970". The
 * DB query flips a true genesis timestamp back to `None` so the
 * frontend renders "genesis" rather than a 56-year-old date.
 */
export type RuntimeUpgrade = { spec_version: number, first_block: string | null, first_block_timestamp_ms: number | null, 
/**
 * `true` for the entry whose `spec_version` matches the current
 * runtime. Recomputed by the handler so history pages always know
 * which row is "live".
 */
is_current: boolean, };
