// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `:code` blob fingerprint. Produced by reading `state_getStorage(":code")`,
 * blake2_256-hashing the raw bytes, and sniffing the first four for the
 * zstd magic (`0x28 0xB5 0x2F 0xFD`) Substrate uses to indicate a
 * compressed WASM. `size_bytes` is the length of the raw (on-chain)
 * blob, not the uncompressed WASM.
 */
export type RuntimeCodeInfo = { 
/**
 * `0x` + 64 hex chars.
 */
hash: string, size_bytes: number, compressed: boolean, };
