// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full `Core_version` decode (matches `sp_version::RuntimeVersion`). All
 * fields are on-chain except `metadata_version`, which is detected once
 * from the bundled metadata blob (see `data::metadata::METADATA_VERSION`).
 * `state_version` is optional because pre-V15 runtimes drop it from the
 * SCALE tail; callers should render it as "unknown" in that case rather
 * than zero.
 */
export type RuntimeIdentity = { spec_name: string, impl_name: string, authoring_version: number, spec_version: number, impl_version: number, transaction_version: number, state_version: number | null, };
