// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeCodeInfo } from "./RuntimeCodeInfo";
import type { RuntimeIdentity } from "./RuntimeIdentity";

/**
 * Everything the runtime page renders: identity, WASM fingerprint,
 * genesis / block context, and the compile-time metadata version.
 *
 * When `at_block` is `None` the snapshot is at the finalized head; when
 * the caller supplied `?at=N`, the block's hash and number are copied
 * here so the UI can label the card with the exact block.
 */
export type RuntimeDetails = { identity: RuntimeIdentity, code: RuntimeCodeInfo, 
/**
 * Chain genesis block hash (`chain_getBlockHash(0)`).
 */
genesis_hash: string, 
/**
 * Block this snapshot was taken at. For the default "latest" call
 * this is the finalized head; for `?at=N` it's the caller's `N`.
 */
at_block: string, at_block_hash: string, 
/**
 * `V14 | V15 | V16` — the version of the compile-time metadata blob
 * used for SCALE decoding (see `data::metadata::METADATA_VERSION`).
 */
metadata_version: number, };
