// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeInfo } from "./EnvelopeInfo";
import type { EpochInfo } from "./EpochInfo";
import type { TreasuryInfo } from "./TreasuryInfo";

/**
 * Token-wide snapshot: balances + epoch state + per-envelope summary.
 */
export type TokenOverview = { symbol: string, decimals: number, total_supply: string, 
/**
 * Free-balance share of supply (= total − locked − envelope reserves).
 */
circulating: string, 
/**
 * Sum of `held` balances across all per-beneficiary holds (= still
 * vesting). Mirrors the pallet's `HoldReason::TokenAllocation`.
 */
locked: string, 
/**
 * Sum of cap remaining inside envelope sub-accounts (undistributed).
 */
envelope_reserves: string, treasury: TreasuryInfo, epoch: EpochInfo, envelopes: Array<EnvelopeInfo>, };
