// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filters for `/transfers`. Phase 3 ships `from` / `to`; `min_amount`
 * is reserved — the UI doesn't render an amount filter yet and a
 * u128-over-string comparison adds a SQL cast we'd rather avoid until
 * it's needed.
 */
export type TransferFilters = { 
/**
 * Sender SS58. Invalid addresses short-circuit to `BadRequest`
 * upstream so the user gets a 400 instead of a silent empty page.
 */
from: string | null, 
/**
 * Recipient SS58. Same error contract as `from`.
 */
to: string | null, };
