// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Extrinsic } from "./Extrinsic";

/**
 * A native-asset transfer, enriched for the list views.
 */
export type Transfer = { extrinsic: Extrinsic, from: string, to: string, amount: string, };
