// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TreasuryInfo = { account: string, balance: string, 
/**
 * Held-under-vesting amount owed to the treasury account (subset of
 * [`TokenOverview::locked`] whose beneficiary is the treasury pot).
 */
locked: string, };
