// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lean projection of [`Block`] for the home-page waveform hero.
 *
 * The hero renders ~72 bars driven by per-block activity. Shipping the
 * full [`Block`] for each bar (~3 kB with the hashes/roots/author)
 * would burn ~250 kB on the seed payload for fields the waveform
 * doesn't read. This struct keeps only what the bar height + tooltip
 * need: counts, ref-time saturation, finalized flag, timestamp.
 */
export type WaveformBlock = { number: string, extrinsic_count: number, event_count: number, ref_time_pct: number, finalized: boolean, timestamp_ms: number, };
